---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: test-requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: packer-dinivas-vault
    image: centos:7
    groups:
      - consul_instances
    published_ports:
      - 0.0.0.0:8200:8200/tcp
    privileged: True
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml
  env:
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY: 'YES'
  lint:
    name: ansible-lint
verifier:
  name: goss
  lint:
    name: yamllint
